inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
