version: '3'
services:
  db:
    image: postgres
    platform: linux/arm64 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/stamp_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
